### ISSUE TITLE
Fail to perform fine-grained module unload

### ISSUE THREAD

**Issue by CNSeniorious000** [promplate/pyth-on-line#30]
When user change some code inside `console/*.py` on [/playground](https://py3.online/playground) and then save it, that module itself should unload but not the parent module `console`. However, it is discovered that if we don't unload `console`, an error will occur when we instantiate another `Console` component. That's because the `console` namespace module no longer have the `.console` attribute.

https://github.com/pyodide/pyodide/pull/4993 would fix this.

> Although e556de4 temporarily fix this by eagerly unload modules, it's not a performant way.

**Comment by CNSeniorious000** [comment]
Note that this bug still exists in corner cases:

On [/console](https://py3.online/console)

```py
import console
del console.console
```

Navigate away and back

```
PythonError: Traceback (most recent call last):
  File "/lib/python312.zip/_pyodide/_base.py", line 655, in pyimport_impl
    res = getattr(res, fromlist[0])
          ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'console' has no attribute 'console'

    at new_error (pyodide.asm.js:10:9965)
    at pyodide.asm.wasm:0x16dc69
    at pyodide.asm.wasm:0x16dd2f
    at Module._pythonexc2js (pyodide.asm.js:10:698851)
    at callPyObjectKwargs (pyodide.asm.js:10:62328)
    at Module.callPyObject (pyodide.asm.js:10:63518)
    at Function.apply (pyodide.asm.js:10:79067)
    at Object.apply (pyodide.asm.js:10:76335)
    at Object.pyimport (pyodide.asm.js:10:106331)
    at Console.S3Gs95Yq.js:2:13170
```
